# Generated by Django 3.0.1 on 2020-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vegdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegname', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
                ('image', models.FileField(upload_to='file')),
                ('des', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
    ]
