# Generated by Django 2.2.1 on 2020-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_vegdet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('st', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vegdet',
            name='oid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vegdet',
            name='category',
            field=models.IntegerField(),
        ),
    ]
