# Generated by Django 2.2.1 on 2020-01-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20200119_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock',
            new_name='stocks',
        ),
    ]
