# Generated by Django 2.2.1 on 2020-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20200119_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
