# Generated by Django 2.2.1 on 2020-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='oid',
            field=models.IntegerField(default=1),
        ),
    ]
