# Generated by Django 3.0.1 on 2020-01-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('rno', models.IntegerField()),
                ('lmark', models.CharField(max_length=20)),
                ('cno', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
