# Generated by Django 3.0.1 on 2020-01-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cname',
        ),
    ]
