# Generated by Django 3.0.1 on 2020-01-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20200107_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
