# Generated by Django 2.2.1 on 2020-01-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
        migrations.AddField(
            model_name='staff',
            name='oid',
            field=models.IntegerField(default=0),
        ),
    ]
